version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    image: version-warehouse
    command: mix phoenix.server
    depends_on:
      - postgres
    volumes:
      - .:/version-warehouse
    ports:
      - "4000:4000"
    restart: always

  setup:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/version-warehouse
    command: "mix ecto.create && mix ecto.migrate"
volumes:
  postgres:
